name: Update README

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Update LeetCode stats
        uses: joshgrec/github-readme-leetcode@v1
        with:
          username: muszic
          output: readme.md
          start-comment: "<!-- leetcode-stats-start -->"
          end-comment: "<!-- leetcode-stats-end -->"

      - name: Update Codeforces stats
        uses: r-priyanshu/codeforces-readme-stats@main
        with:
          handle: Muujic
          output_path: readme.md
          start_comment: "<!-- codeforces-stats-start -->"
          end_comment: "<!-- codeforces-stats-end -->"

      - name: Commit changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "Update LeetCode and Codeforces stats" || echo "No changes to commit"
          git push
